when:
  event: [push]

steps:
  build:
    image: node:22
    commands:
      - corepack enable
      - corepack pnpm install --frozen-lockfile
      - corepack pnpm run build
  deploy:
    image: woodpeckerci/plugin-git-push
    settings:
      branch: pages
      remote: https://codeberg.org/BrokenShine/pages.git
      force: true
      commit: true
      path: dist
      local_branch: main
    secrets: [git_push_token]
