#+TITLE: 新年伊始，来做点特别的事吧
#+DATE: <2026-03-03 Tue 02:46>
#+FILETAGS: :生活:

没想到又过了一年啊...... 我永远都在觉得"自己今年怎么什么都没干就过去了", 但实际上要真说的话, 做的事情其实是不少的.
所以我决定给自己开一个 blog 站, 用来记录自己的一些日常, 或者说是自己的思考之类的.

* 为什么要记录自己?

首先要说的一点, 就是 *看着自己以前的样子,很好玩*.
我有事没事的时候, 就特别喜欢翻看自己以前留下的痕迹, 虽说我可能把最有价值但是最有毒的那一段给人为地抹除掉了, 但是实际上看下来还是很令人感慨的, 所以说, 我想要有选择性地记录一下我想要记录的内容, 一直留档给未来的我看, 二是能够记录自己的生活, 来让自己看着更像是"做了不少事"的样子.

* 为什么要建站?

简而言之, 目的其实是为了 *学习*.
我还是想要通过写一些前端的东西, 比如说根据我这里正在使用的主题进行修改啊之类的, 来学习一些前端的知识.
"实操"永远是一个学习各种东西的好办法, 因为实际操作一遍的话, 比单单地看着纸面上的知识会更具有"互动性", 你可以操作你学过的东西, 借此来深入了解, 并加深印象, 我认为这是一件很好的事.
毕竟我也不知道未来到底会成为什么样, 所以也只能想方设法地打磨一下自己, 让自己多学点东西, 这样也方便未来找到适合自己的工作或路径之类的.

* 我会记录什么?

我大概会在最近先想办法用 ai 把自己录过的几个视频的文案给扒下来, 润色之后再发出来吧.
那些视频基本上都是我梦到什么说什么, 但是意外地赞同的人很多, 还是蛮神奇的, 所以我也想要重新润色一下, 顺便再加上一些自己的见解. 以后的评论类视频, 我也会尽量地尝试去先撰写一份稿子, 然后再录制, 这样逻辑性和组织性也会更强, 能够传递更多的有效信息.
同时, 假如我在折腾某样东西并且成功了的话, 我也会把这些步骤给记录下来, 并放到博客里面, 这样也能防止未来的自己踩雷, 或是给他人提供参考文档.
新年总结或感悟的话, 尽量每年都写一篇吧, 像是这一篇文章, 我实际上是把它当作自己上一年的总结, 以及下一年的展望来看待的, 所以会打上一个"总结"的 tag.

总之, 我想朝着未来的方向不断前进, 想成为心目中的自己, 希望这个博客能够帮助到自己, 也希望能够帮助到在翻这个博客的大家, 感谢各位的支持和陪伴, 才能让我有着前行的动力.
